:pygments-style: tango
:source-highlighter: coderay
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font
:imagesdir: images/

=== Demonstration - Managing Sensitive Information With Secrets

.Managing Sensitive Information With Secrets - Demo
=====

[TIP]
====
Must start the lab for the demo to work so resources will be available and usable.

[source,bash]
----
[student@workstation ~]$ lab authorization-secrets start
----
====

. Source the resource file and login as a developer user
+
[source,bash]
----
[student@workstation ~]$ source /usr/local/etc/ocp4.config

[student@workstation ~]$ oc login -u developer -p developer
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
----

. Create a project
+
[source,bash]
----
[student@workstation ~]$ oc new-project demo-secrets
Now using project "demo-secrets" on server "https://api.ocp-gdqpjexgnzgogxx200728.do280.rht-na.nextcle.com:6443".
----

. Create secrets for the project
+
[source,bash]
----
[student@workstation ~]$ oc create secret generic mysql --from-literal user=demouser --from-literal password=redhat --from-literal database=demo_db --from-literal hostname=mysql
secret/mysql created
----

. Create an Application
+
[source,bash]
----
[student@workstation ~]$ oc new-app --name mysql-demo --docker-image registry.access.redhat.com/rhscl/mysql-57-rhel7:5.7-47
--> Found container image 77d20f2 (12 months old) from registry.access.redhat.com for "registry.access.redhat.com/rhscl/mysql-57-rhel7:5.7-47"
----

. Check status of deployed application
+
[source,bash]
----
[student@workstation ~]$ oc get pods -w
NAME                  READY   STATUS              RESTARTS   AGE
mysql-demo-1-9vhjq    0/1     ContainerCreating   0          27s
mysql-demo-1-deploy   1/1     Running             0          35s
NAME                  READY   STATUS              RESTARTS   AGE
mysql-demo-1-9vhjq    0/1     Error               0          44s
mysql-demo-1-9vhjq    0/1     Error               1          45s
mysql-demo-1-9vhjq    0/1     CrashLoopBackOff    1          46s
----

. Investigate issues
+
[source,bash]
----
[student@workstation ~]$ oc logs mysql-demo-1-9vhjq
=> sourcing 20-validate-variables.sh ...
You must either specify the following environment variables:
  MYSQL_USER (regex: '^[a-zA-Z0-9_]+$')
  MYSQL_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
  MYSQL_DATABASE (regex: '^[a-zA-Z0-9_]+$')
Or the following environment variable:
  MYSQL_ROOT_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
Or both.
----
+
.Variables needed by container image
[IMPORTANT]
====
In this instance, the container couldn't start because the environment variables weren't passed to the container or made available via the secrets
====

. Update the deployment configuration and check to see if the pod is fixed
+
.Updating the *dc*
[source,bash]
----
[student@workstation ~]$ oc set env deployment/mysql-demo --prefix MYSQL_ --from secret/mysql
deploymentconfig.apps.openshift.io/mysql-demo updated
----
+
.Alternate methods of deployment config manipulation
[CAUTION]
====
It is important to note that the *oc set env* is setting all environment variables and adding a prefix of *MYSQL_* to all the variables that have been defined. It is also possible to use the *oc edit dc/mysql-demo* to modify the deployment configuration.

[source,bash]
----
[student@workstation ~]$ oc edit deployment/mysql-demo

... output omitted ...

kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-07-28T17:11:02Z"
  generation: 3
  labels:
    app: mysql-demo
  name: mysql-demo
  namespace: demo-secrets

... output omitted ...

spec:
  containers:
  - env:
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: database
          name: mysql
    - name: MYSQL_HOSTNAME
      valueFrom:
        secretKeyRef:
          key: hostname
          name: mysql
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: mysql

... output omitted ...
----
+
====

.Note about oc edit dc/_name_
[TIP]
====
With OCP v4.5, the *oc edit dc/name* no longer works as it doesn't see that as a deployment config. Instead, you need to use *oc edit deployment/name* so it will find the deployment based on the name of the App you specified earlier.
====
+
.Verifying application and pods
[source,bash]
----
[student@workstation ~]$  oc get pods
NAME                  READY   STATUS      RESTARTS   AGE
mysql-demo-2-deploy   0/1     Completed   0          24s
mysql-demo-2-spbpj    1/1     Running     0          15
----

. Test the Database with *oc rsh*
+
[source,bash]
----
[student@workstation ~]$ oc rsh mysql-demo-2-spbpj
sh-4.2$
----
+
.Accessing the Database
[source,bash]
----
sh-4.2$ mysql -u demouser -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7

... output omitted ...

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| demo_db            |
+--------------------+
2 rows in set (0.00 sec)

mysql> exit
Bye
sh-4.2$ exit
exit
----

. Cleanup the demo
+
.Source Description
[source,bash]
----
[student@workstation ~]$ oc delete projects demo-secrets
project.project.openshift.io "demo-secrets" deleted

[student@workstation ~]$ lab authorization-secrets finish
----

=====
