:pygments-style: tango
:source-highlighter: coderay
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font
:imagesdir: images/

=== Demonstration - Configuring Identity Providers

.Configuring Identity Providers - Demo
=====

Do not run the *lab auth-provider start* in home environment.


.Prepare the Lab Environment for Demo
[WARNING]
====

If running the prepare environment, it gets rid of all configured Identity Providers, not just providers configured for the lab.

[source,bash]
----
[student@workstation ~]$ lab auth-provider start

Checking prerequisites for Guided Exercise: Configuring Identity Providers

 Verify the OpenShift cluster is running:
 · Check master node 'ocp4-7h47x-master-0' is ready............  SUCCESS
 · Check master node 'ocp4-7h47x-master-1' is ready............  SUCCESS
 · Check master node 'ocp4-7h47x-master-2' is ready............  SUCCESS
 Checking for conflicts with existing OpenShift projects:
 · The 'auth-provider' project is absent.......................  SUCCESS

Setting up the classroom for Guided Exercise: Configuring Identity Providers

 Preparing the student's workstation:
 · Download exercise files.....................................  SUCCESS
 · Download solution files.....................................  SUCCESS
 Restoring authentication settings to installation defaults:
 · Remove HTPasswd secret: 'htp-secret-home'...................  SUCCESS
 · Remove all configured Identity Providers....................  SUCCESS
 · Remove all existing users...................................  SUCCESS
 · Remove all existing identities..............................  SUCCESS

Overall start status...........................................  SUCCESS
----

====


. Login to OpenShift
+
.Sourcing the *ocp4.config* file and Logging Into OCP
[source,bash]
----
[student@workstation ~]$ source /usr/local/etc/ocp4.config

[student@workstation ~]$ oc login -u kubeadmin -p ${RHT_OCP4_KUBEADM_PASSWD} ${RHT_OCP4_MASTER_API}
Login successful.

You have access to 58 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default"
----

. Create a password file for use
+
.Creating the file with *htpasswd* and adding the *admin* user
[source,bash]
----
[student@workstation ~]$ htpasswd -c -B -b My_OCP_Users admin1 redhat
Adding password for user admin1
----
+
.A Note about *htpasswd* Options
[TIP]
====
For initially creating the file, you will use a *-c* and a *-B* option to create the file and specify _bcrypt_ as the type of encryption. Any other users and people added to the file will just have the *-b* option used.
====

. Add additional users to the password file
+
.Using *htpasswd* to add additional users
[source,bash]
----
[student@workstation ~]$ htpasswd My_OCP_Users demo1
New password:
Re-type new password:
Adding password for user demo1
----
+
.*htpasswd* Syntax
[IMPORTANT]
====
It is important to note that the *-b* option takes the password as an argument from the command line. In environments where there is a concern with security, the password should be entered interactively.
====

. Examine the user password file
+
.Output of the *My_OCP_Users* File
[source,bash]
----
[student@workstation ~]$ cat My_OCP_Users
admin:$2y$05$Cw5l91Lyiw1rj.EBcSQZZO9Z7G9Jr6CNtgPZkDqSSD41CuqduCtUy
demo1:$apr1$nKOXYMrl$VJUJ8mDeMQmFb/XwyXh090
----

. Create OCP Password Identity Provider
+
.Creation of OCP Secret Resource
[source,bash]
----
[student@workstation ~]$ oc create secret generic do280-users --from-file htpasswd=My_OCP_Users -n openshift-config
secret/do280-users created
----
+
.Creating an OCP Secret
[NOTE]
====
In the command above, we are creating an OCP secret named *do280-users*. This is the filename that will be used as a resource to hold the authentication information for the *oauth* cluster resource.
====

. Give admin user permissions and a role
+
.Use *oc adm policy* to add role to user
[source,bash]
----
[student@workstation ~]$  oc adm policy add-cluster-role-to-user cluster-admin admin1
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "admin1"

[student@workstation ~]$  oc adm policy add-cluster-role-to-user cluster-admin demo
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "demo"
----

. Update *HTPasswd* Identify Provider for OCP
+
.Use *oc get* to get the resource
[source,bash]
----
[student@workstation ~]$ oc get -o yaml oauth cluster > oauth.yaml
----
+
.Edit the Resource
[source,bash]
----
[student@workstation ~]$ vim oauth.yaml
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: do280-users
    mappingMethod: claim
    name: do280-idp
    type: HTPasswd
----
+
.Replace the Resource
[source,bash]
----
[student@workstation ~]$  oc replace -f oauth.yaml
oauth.config.openshift.io/cluster replaced
----
+
.Modifying Users or Passwords
[WARNING]
====
It is important to replace the secret file (resource) in OCP if new users are added or the password is updated. The old way was to do a dry-run on the CLI. This still works but generates a warning, stating you need to use *--dry-run=client*.

.Modifying/Adding Users
[source,bash]
----
[student@workstation ~]$ oc create secret generic do280-users --from-file htpasswd=My_OCP_Users --dry-run -o yaml | oc replace -n openshift-config -f -
secret/do280-users replaced
----
====
+
.OCPv4.5 Method of Updating Secrets
[IMPORTANT]
====
[student@workstation ~]$ oc set data secret/do280-users \
 --from-file htpasswd=/home/student/My_OCP_Users \
 -n openshift-config
====

. Test the Login
+
.Time for Resource to Update
[CAUTION]
====
It should be noted that it might be possible to end up with a "Login failed" message. This is generally because the authorization pods haven't fully updated.

[source,bash]
----
[student@workstation ~]$ oc login -u admin1 https://api.ocp4.example.com:6443
Authentication required for https://api.ocp4.example.com:6443 (openshift)
Username: admin1
Password:
Login failed (401 Unauthorized)
Verify you have provided correct credentials.

[student@workstation ~]$ oc login -u admin1 https://api.ocp4.example.com:6443
Authentication required for https://api.ocp4.example.com:6443 (openshift)
Username: admin1
Password:
Login successful.
----

In this instance you can generally try the login again after some time has passed.
====
+
.Testing the Admin User
[source,bash]
----
[student@workstation ~]$ oc login -u admin1 https://api.ocp4.example.com:6443
Authentication required for https://api.ocp4.example.com:6443 (openshift)
Username: admin1
Password:
Login successful.
----
+
.Testing the Demo User
[source,bash]
----
[student@workstation ~]$ oc login
Authentication required for https://api.ocp4.michettetech.com:6443 (openshift)
Username: demo1
Password:
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
----


=====
